# Define tu servicio de Static Site
services:
  - type: static
    name: formulario-la-regional
    rootDir: . # La raíz del repositorio
    buildCommand: npm run build
    staticPublishPath: dist # La carpeta que Render debe servir
    pullRequest:
      autoDeploy: true
    # **REGLA DE REDIRECCIÓN DIRECTA**
    routes:
      - type: rewrite
        source: /admin-login
        destination: /index.html
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /registro-exitoso
        destination: /index.html
      # Regla catch-all (opcional, si las demás fallan)
      - type: rewrite
        source: /
        destination: /index.html